//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CO5027.Entite
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SaPEEntitiesRemote : DbContext
    {
        public SaPEEntitiesRemote()
            : base("name=SaPEEntitiesRemote")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<item_pushcart> item_pushcart { get; set; }
        public virtual DbSet<item_table> item_table { get; set; }
        public virtual DbSet<item_versions> item_versions { get; set; }
    }
}
