//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CO5027.Entite
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_customer
    {
        public int Code { get; set; }
        public string AUQCode { get; set; }
        public string Surname { get; set; }
        public string Forename { get; set; }
        public string Address { get; set; }
        public int ZipCode { get; set; }
        public string EmailAddress { get; set; }
    }
}
