//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CO5027.Entite
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_pushcart
    {
        public string UserCode { get; set; }
        public bool PushCart { get; set; }
        public int ItemCode { get; set; }
        public Nullable<System.DateTime> BuyDate { get; set; }
        public int Total { get; set; }
        public int Code { get; set; }
    
        public virtual item_table item_table { get; set; }
    }
}
