//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CO5027.Entite
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public item_table()
        {
            this.item_pushcart = new HashSet<item_pushcart>();
        }
    
        public string ItemName { get; set; }
        public int Versions { get; set; }
        public string ItemDetails { get; set; }
        public Nullable<decimal> ItemCostBND { get; set; }
        public string ItemDisplay { get; set; }
        public int Code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<item_pushcart> item_pushcart { get; set; }
        public virtual item_versions item_versions { get; set; }
    }
}
